# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/edb/gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 676)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_Console = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_Console.setObjectName("groupBox_Console")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_Console)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.plainTextEdit_Console = QtWidgets.QPlainTextEdit(self.groupBox_Console)
        self.plainTextEdit_Console.setObjectName("plainTextEdit_Console")
        self.verticalLayout_3.addWidget(self.plainTextEdit_Console)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_ConsoleInput = QtWidgets.QLineEdit(self.groupBox_Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_ConsoleInput.sizePolicy().hasHeightForWidth())
        self.lineEdit_ConsoleInput.setSizePolicy(sizePolicy)
        self.lineEdit_ConsoleInput.setObjectName("lineEdit_ConsoleInput")
        self.horizontalLayout.addWidget(self.lineEdit_ConsoleInput)
        self.pushButton_ConsoleClear = QtWidgets.QPushButton(self.groupBox_Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConsoleClear.sizePolicy().hasHeightForWidth())
        self.pushButton_ConsoleClear.setSizePolicy(sizePolicy)
        self.pushButton_ConsoleClear.setObjectName("pushButton_ConsoleClear")
        self.horizontalLayout.addWidget(self.pushButton_ConsoleClear)
        self.line = QtWidgets.QFrame(self.groupBox_Console)
        self.line.setLineWidth(10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButton_ConsoleSendInput = QtWidgets.QPushButton(self.groupBox_Console)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ConsoleSendInput.sizePolicy().hasHeightForWidth())
        self.pushButton_ConsoleSendInput.setSizePolicy(sizePolicy)
        self.pushButton_ConsoleSendInput.setObjectName("pushButton_ConsoleSendInput")
        self.horizontalLayout.addWidget(self.pushButton_ConsoleSendInput)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_Console)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EDB"))
        self.groupBox_Console.setTitle(_translate("MainWindow", "Console"))
        self.pushButton_ConsoleClear.setText(_translate("MainWindow", "Send Input"))
        self.pushButton_ConsoleSendInput.setText(_translate("MainWindow", "Clear Console"))
