#define BUILD_WITH_TESTS
#define BUILD_DEBUG
#ifdef BUILD_DEBUG
	extern bool PRINT_STACK_AFTER_THREAD_END;
	extern bool PRINT_STACK_AFTER_INSTR_EXECUTION;
	extern bool PRINT_INSTR_BEFORE_EXECUTION;
#endif
