#pragma once

#define OP_CODES NOOP, PUSH, POP, IADD, ISUB, IMUL, IDIV, DADD, DSUB, DMUL, DDIV, JUMP, JUMPZ, JUMPNZ, SYSCALL, EXIT
#define SYSCALL_CODES EXIT, PRINTC, PRINTS, MALLOC, FREE
#define INSTRUCTION_SIZES 1, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9, 9, 9, 2, 1
#define WORD_SIZE 8
#define OP_CODE_SIZE 1